### ISSUE TITLE
Error: Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by brianmcmillan** [alanhoff/node-hapi-faker#1]
Installed with npm but when initializing the server, received a message that bluebird could not be found.

Installed with:
$ npm install --save hapi-faker
npm WARN package.json mock@0.0.1 No repository field.
hapi-faker@1.1.0 node_modules/hapi-faker
├── mout@0.11.0
├── faker@2.1.5
├── joi@6.6.1 (topo@1.0.3, isemail@1.1.1, hoek@2.14.0, moment@2.10.6)
└── json-schema-faker@0.1.13 (deref@0.3.0, chance@0.7.6, randexp@0.4.0)

Start server:
$ node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/brianmcmillan/GitHub/mock/node_modules/hapi-faker/lib/hapi-faker.js:4:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by alanhoff** [comment]
That's awkward, bluebird was listed on devDependencies, 1cae780b0d4159cdc9fc9f531b29895647c74aab should fix this.

**Comment by brianmcmillan** [comment]
Thanks! Works perfectly.
~ brian
