### ISSUE TITLE
jsf error on registration setup

### ISSUE THREAD

**Issue by vijays-cheruks** [alanhoff/node-hapi-faker#2]
I've followed the setup instructions given, but see the following error trace during the plug-in registration on Hapi server 14.x ...

`ValidationError: child "jfs" fails because ["jfs" must be a Function]
    at Object.exports.process (/home/vijay/Worklab/hapi-bootup/node_modules/hapi-faker/node_modules/joi/lib/errors.js:140:17)
    at internals.Any._validateWithOptions (/home/vijay/Worklab/hapi-bootup/node_modules/hapi-faker/node_modules/joi/lib/any.js:654:25)
    at root.validate (/home/vijay/Worklab/hapi-bootup/node_modules/hapi-faker/node_modules/joi/lib/index.js:100:23)
    at new HapiFaker (/home/vijay/Worklab/hapi-bootup/node_modules/hapi-faker/lib/hapi-faker.js:10:20)
    at Object.exports.register (/home/vijay/Worklab/hapi-bootup/node_modules/hapi-faker/index.js:7:14)
    at Object.target [as register] (/home/vijay/Worklab/hapi-bootup/node_modules/joi/lib/object.js:77:34)
    at each (/home/vijay/Worklab/hapi-bootup/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/home/vijay/Worklab/hapi-bootup/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/vijay/Worklab/hapi-bootup/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.each [as register] (/home/vijay/Worklab/hapi-bootup/node_modules/hapi/lib/plugin.js:320:11)
    at Object.<anonymous> (/home/vijay/Worklab/hapi-bootup/server.js:27:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
`

Please advise

Thanks

**Comment by ksingh0810** [comment]
ValidationError: child "jfs" fails because ["jfs" must be a Function]

**Comment by alanhoff** [comment]
Do you have an example on how you're configuring the route?

**Comment by ksingh0810** [comment]
{
      plugin: 'hapi-faker',
      options: {}
    },
    {
      plugin: 'inert',
      options: {}
    },
    {
      plugin: 'vision',
      options: {}
    },
the other plugins work fine
it fails to register
